const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d');
const screens={title:$('titleScreen'),menu:$('menuScreen'),game:$('gameScreen')};
const ui={start:$('startBtn'),play:$('playBtn'),reset:$('resetBtn'),return:$('returnBtn'),dialogue:$('dialogue'),speaker:$('speaker'),dialogueText:$('dialogueText'),dialogueNext:$('dialogueNext'),end:$('endCard'),reward:$('rewardSummary'),health:$('healthText'),cash:$('cashText'),mission:$('missionText'),pad:$('padStatus')};
const SAVE_KEY='fastLnBeanieBeatdownV5';
const baseSave={cash:0,xp:0,level:1,rep:0,points:2,perkPoints:1,runs:0,wins:0,streak:0,bestStreak:0,stats:{strength:1,toughness:1,speed:1,technique:1},perks:{pressure:0,collector:0,secondWind:0,momentum:0}};
let save=loadSave();
function loadSave(){try{return Object.assign(structuredClone(baseSave),JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'))}catch{return structuredClone(baseSave)}}
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save))}
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function xpNeeded(level){return 100+(level-1)*55}
function refreshHQ(){
 $('menuCash').textContent='$'+save.cash;$('runCount').textContent=save.runs+' runs';$('levelText').textContent=save.level;$('xpText').textContent=save.xp+' / '+xpNeeded(save.level);$('repText').textContent=save.rep;$('streakText').textContent=save.bestStreak;$('pointsText').textContent=save.points;$('perkPointsText').textContent=save.perkPoints;
 Object.entries(save.stats).forEach(([k,v])=>$(k+'Text').textContent=v);
 Object.entries(save.perks).forEach(([k,v])=>$(k+'Rank').textContent='Rank '+v);
 const pressure=1+save.runs*.18;const cash=Math.round((100+save.runs*18)*(1+save.perks.collector*.15));const xp=Math.round((60+save.runs*8)*(1+save.perks.momentum*save.streak*.05));
 $('difficultyText').textContent='District pressure: '+pressure.toFixed(1)+'×';$('projectedReward').textContent='$'+cash+' · '+xp+' XP';
 document.querySelectorAll('[data-upgrade]').forEach(b=>b.disabled=save.points<1);document.querySelectorAll('[data-perk]').forEach(b=>b.disabled=save.perkPoints<1);
}
ui.start.onclick=()=>{showScreen('menu');refreshHQ()};
ui.play.onclick=()=>startRun();
ui.return.onclick=()=>{ui.end.classList.add('hidden');showScreen('menu');refreshHQ()};
ui.reset.onclick=()=>{if(confirm('Reset all Beanie progression?')){save=structuredClone(baseSave);persist();refreshHQ()}};
document.querySelectorAll('[data-upgrade]').forEach(btn=>btn.onclick=()=>{if(save.points<1)return;save.points--;save.stats[btn.dataset.upgrade]++;persist();refreshHQ()});
document.querySelectorAll('[data-perk]').forEach(btn=>btn.onclick=()=>{if(save.perkPoints<1)return;save.perkPoints--;save.perks[btn.dataset.perk]++;persist();refreshHQ()});

const keys={left:false,right:false,jump:false,attack:false,heavy:false,dodge:false};
const pad={left:false,right:false,jump:false,attack:false,heavy:false,dodge:false,connected:false,prev:[]};
let running=false,last=0,cameraX=0,runCash=0,levelComplete=false,gameOver=false,introIndex=0,enemies=[];
const world={width:2600,ground:430,exitX:2350};
const player={x:120,y:350,w:54,h:78,vx:0,vy:0,speed:260,jump:590,onGround:false,facing:1,health:100,maxHealth:100,attackTimer:0,heavyTimer:0,dodgeTimer:0,invuln:0,hitFlash:0};
const intro=[['BEANIE','Everybody keep asking what the movement is.'],['LEDGER','Because you still have not explained it.'],['BEANIE','It is simple. Be down… or beat down.'],['LEDGER','That sounds like two different threats.'],['BEANIE','I do not repeat myself. Open the gate.']];
function createEnemies(){const scale=1+save.runs*.18;return[{x:760,y:362,w:52,h:68,hp:Math.ceil(4*scale),maxHp:Math.ceil(4*scale),dir:-1,speed:86+save.runs*2,attackTimer:0,attackCooldown:.5,hitFlash:0},{x:1280,y:362,w:52,h:68,hp:Math.ceil(4*scale),maxHp:Math.ceil(4*scale),dir:-1,speed:92+save.runs*2,attackTimer:0,attackCooldown:.8,hitFlash:0},{x:1820,y:362,w:52,h:68,hp:Math.ceil(6*scale),maxHp:Math.ceil(6*scale),dir:-1,speed:78+save.runs*2,attackTimer:0,attackCooldown:.3,hitFlash:0}]}
function startRun(){showScreen('game');runCash=0;levelComplete=false;gameOver=false;cameraX=0;introIndex=0;enemies=createEnemies();Object.assign(player,{x:120,y:350,vx:0,vy:0,health:100+save.stats.toughness*18,maxHealth:100+save.stats.toughness*18,speed:250+save.stats.speed*18,jump:590,attackTimer:0,heavyTimer:0,dodgeTimer:0,invuln:0,hitFlash:0});ui.cash.textContent='$0';ui.health.textContent=player.health+' HP';ui.end.classList.add('hidden');showDialogue(0);draw()}
function showDialogue(i){introIndex=i;ui.speaker.textContent=intro[i][0];ui.dialogueText.textContent=intro[i][1];ui.dialogue.classList.remove('hidden');running=false}
function advanceDialogue(){if(++introIndex<intro.length)showDialogue(introIndex);else{ui.dialogue.classList.add('hidden');running=true;last=performance.now();requestAnimationFrame(loop)}}
ui.dialogueNext.onclick=advanceDialogue;
addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=true;if(['ArrowRight','d','D'].includes(e.key))keys.right=true;if([' ','w','W','ArrowUp'].includes(e.key))keys.jump=true;if(['j','J','Enter'].includes(e.key))keys.attack=true;if(['k','K'].includes(e.key))keys.heavy=true;if(['l','L','Shift'].includes(e.key))keys.dodge=true});
addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false;if([' ','w','W','ArrowUp'].includes(e.key))keys.jump=false;if(['j','J','Enter'].includes(e.key))keys.attack=false;if(['k','K'].includes(e.key))keys.heavy=false;if(['l','L','Shift'].includes(e.key))keys.dodge=false});
document.querySelectorAll('[data-key]').forEach(btn=>{const k=btn.dataset.key;const on=e=>{e.preventDefault();keys[k]=true};const off=e=>{e.preventDefault();keys[k]=false};btn.addEventListener('pointerdown',on);btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off);btn.addEventListener('pointerleave',off)});
function down(gp,i){return !!gp?.buttons?.[i]?.pressed}function once(gp,i){const n=down(gp,i),o=!!pad.prev[i];pad.prev[i]=n;return n&&!o}
function controllerLoop(){const gp=Array.from(navigator.getGamepads?navigator.getGamepads():[]).find(Boolean);if(gp){pad.connected=true;ui.pad.textContent='Controller connected: '+(gp.id||'Gamepad');const x=gp.axes?.[0]||0;pad.left=x<-.22||down(gp,14);pad.right=x>.22||down(gp,15);if(once(gp,0)){if(screens.title.classList.contains('active'))ui.start.click();else if(screens.menu.classList.contains('active'))ui.play.click();else if(!ui.dialogue.classList.contains('hidden'))advanceDialogue();else if(!ui.end.classList.contains('hidden'))ui.return.click();else pad.jump=true}if(once(gp,2))pad.attack=true;if(once(gp,3))pad.heavy=true;if(once(gp,1))pad.dodge=true}else{pad.connected=false;pad.left=pad.right=false}requestAnimationFrame(controllerLoop)}requestAnimationFrame(controllerLoop);
function damageMultiplier(){return (1+save.stats.strength*.12)*(1+save.perks.pressure*.12)}
function hitEnemy(e,base,force){if(e.hp<=0||e.hitFlash>0)return;const crit=Math.random()<save.stats.technique*.035;const dmg=Math.max(1,Math.round(base*damageMultiplier()*(crit?2:1)));e.hp-=dmg;e.hitFlash=.15;e.x+=player.facing*force;if(e.hp<=0){runCash+=25+(e.maxHp>6?15:0);ui.cash.textContent='$'+runCash;player.health=Math.min(player.maxHealth,player.health+save.perks.secondWind*8)}}
function hurtPlayer(dmg,force){if(player.invuln>0||gameOver||levelComplete)return;player.health=Math.max(0,player.health-dmg);player.invuln=.75;player.hitFlash=.2;player.vx=force;player.vy=-180;if(player.health<=0){gameOver=true;running=false;save.streak=0;persist();ui.mission.textContent='BEANIE GOT SAT DOWN — return to HQ';setTimeout(()=>{showScreen('menu');refreshHQ()},900)}}
function finishLevel(){if(levelComplete)return;levelComplete=true;running=false;const cashReward=Math.round((100+save.runs*18+runCash)*(1+save.perks.collector*.15));const xpReward=Math.round((60+save.runs*8)*(1+save.perks.momentum*save.streak*.05));const repReward=10+Math.floor(save.runs/2)+save.perks.momentum*save.streak;save.cash+=cashReward;save.xp+=xpReward;save.rep+=repReward;save.runs++;save.wins++;save.streak++;save.bestStreak=Math.max(save.bestStreak,save.streak);save.points+=1;if(save.wins%2===0)save.perkPoints+=1;let leveled=0;while(save.xp>=xpNeeded(save.level)){save.xp-=xpNeeded(save.level);save.level++;save.points+=2;save.perkPoints+=1;leveled++}persist();ui.reward.innerHTML='<b>+$'+cashReward+'</b> career cash<br>+'+xpReward+' XP · +'+repReward+' reputation<br>+1 upgrade point'+(save.wins%2===0?' · +1 perk token':'')+(leveled?'<br><strong>LEVEL UP! Bonus points awarded.</strong>':'');ui.end.classList.remove('hidden');ui.mission.textContent='RUN COMPLETE';draw()}
function update(dt){player.invuln=Math.max(0,player.invuln-dt);player.hitFlash=Math.max(0,player.hitFlash-dt);player.attackTimer=Math.max(0,player.attackTimer-dt);player.heavyTimer=Math.max(0,player.heavyTimer-dt);player.dodgeTimer=Math.max(0,player.dodgeTimer-dt);player.vx=0;const l=keys.left||pad.left,r=keys.right||pad.right;if(player.dodgeTimer<=0){if(l){player.vx=-player.speed;player.facing=-1}if(r){player.vx=player.speed;player.facing=1}}if((keys.jump||pad.jump)&&player.onGround){player.vy=-player.jump;player.onGround=false;keys.jump=pad.jump=false}if((keys.dodge||pad.dodge)&&player.dodgeTimer<=0){player.dodgeTimer=.32;player.invuln=.42;player.vx=player.facing*(500+save.stats.speed*18);keys.dodge=pad.dodge=false}if(player.dodgeTimer>0)player.vx=player.facing*(500+save.stats.speed*18);if((keys.attack||pad.attack)&&player.attackTimer<=0&&player.heavyTimer<=0){player.attackTimer=.28;keys.attack=pad.attack=false}if((keys.heavy||pad.heavy)&&player.heavyTimer<=0&&player.attackTimer<=0){player.heavyTimer=.52;keys.heavy=pad.heavy=false}player.vy+=1500*dt;player.x+=player.vx*dt;player.y+=player.vy*dt;if(player.y+player.h>=world.ground){player.y=world.ground-player.h;player.vy=0;player.onGround=true}player.x=Math.max(0,Math.min(world.width-player.w,player.x));enemies.forEach(e=>{e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer=Math.max(0,e.attackTimer-dt);e.attackCooldown=Math.max(0,e.attackCooldown-dt);if(e.hp<=0)return;const dx=player.x-e.x,dist=Math.abs(dx);e.dir=Math.sign(dx)||e.dir;if(dist<420&&dist>70)e.x+=e.dir*e.speed*dt;if(dist<=74&&e.attackCooldown<=0){e.attackTimer=.34;e.attackCooldown=Math.max(.58,1.05-save.runs*.025)}if(e.attackTimer>.16&&e.attackTimer<.22)hurtPlayer(8+Math.floor(save.runs*.8),e.dir*220);if(dist<82&&Math.abs(player.y-e.y)<84){if(player.attackTimer>.12&&player.attackTimer<.2)hitEnemy(e,1,62);if(player.heavyTimer>.20&&player.heavyTimer<.32)hitEnemy(e,2+save.stats.technique*.25,110)}});cameraX=Math.max(0,Math.min(world.width-canvas.width,player.x-220));const alive=enemies.filter(e=>e.hp>0).length;if(alive===0){ui.mission.textContent='Courtyard cleared — reach the green exit';if(player.x>=world.exitX)finishLevel()}else if(player.x>700)ui.mission.textContent='Clear the courtyard ('+alive+' left)';ui.health.textContent=player.health+' / '+player.maxHealth+' HP'+(pad.connected?' · PAD':'')}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x-cameraX,y,w,h)}
function drawBackground(){ctx.fillStyle='#76c6d7';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#ffd27d';ctx.fillRect(0,320,canvas.width,220);for(let i=0;i<12;i++){const x=i*240-cameraX*.35;ctx.fillStyle=i%2?'#82563f':'#6f4938';ctx.fillRect(x,150,190,180);ctx.fillStyle='#eac8a8';for(let w=0;w<3;w++)ctx.fillRect(x+24+w*52,190,30,46)}rect(0,world.ground,world.width,110,'#494f5d');for(let i=0;i<world.width;i+=90)rect(i,world.ground+48,55,7,'#f7d66b');ctx.fillStyle='#111';ctx.font='bold 28px system-ui';ctx.fillText('SOUTH COVE COURTYARD',40-cameraX*.15,80)}
function drawBean(x,y,w,h,skin,hoodie,facing=1,enemy=false,flash=false){ctx.save();ctx.translate(x-cameraX+w/2,y+h/2);ctx.scale(facing,1);ctx.fillStyle=flash?'#fff':hoodie;ctx.beginPath();ctx.roundRect(-w/2,-h/4,w,h*.68,22);ctx.fill();ctx.fillStyle=flash?'#fff':skin;ctx.beginPath();ctx.arc(0,-h*.27,w*.34,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(-w*.34,-h*.48,w*.68,10);ctx.fillRect(8,-h*.3,5,5);ctx.fillStyle=enemy?'#ef4444':'#f4f4f5';ctx.fillRect(-w*.25,h*.35,w*.22,10);ctx.fillRect(w*.04,h*.35,w*.22,10);ctx.fillStyle=flash?'#fff':skin;ctx.beginPath();ctx.arc(w*.48,0,10,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-w*.48,0,10,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){drawBackground();rect(520,345,120,85,'#7c3aed');rect(1050,300,180,130,'#111827');rect(2050,250,220,180,'#7f1d1d');ctx.fillStyle='#fff';ctx.font='bold 22px system-ui';ctx.fillText('BARBERSHOP',2060-cameraX,290);if(enemies.length&&enemies.every(e=>e.hp<=0)){rect(world.exitX,270,130,160,'#16a34a');ctx.fillStyle='#fff';ctx.font='bold 24px system-ui';ctx.fillText('EXIT',world.exitX-cameraX+32,315)}enemies.forEach(e=>{if(e.hp>0){drawBean(e.x,e.y,e.w,e.h,'#9a623f','#7f1d1d',e.dir,true,e.hitFlash>0);ctx.fillStyle='#111';ctx.fillRect(e.x-cameraX,e.y-12,e.w,6);ctx.fillStyle='#ef4444';ctx.fillRect(e.x-cameraX,e.y-12,e.w*Math.max(0,e.hp/e.maxHp),6)}});drawBean(player.x,player.y,player.w,player.h,'#9b6546','#1f2937',player.facing,false,player.hitFlash>0);if(player.attackTimer>0||player.heavyTimer>0){ctx.strokeStyle=player.heavyTimer>0?'#ff7a1a':'#ffe66d';ctx.lineWidth=player.heavyTimer>0?13:8;ctx.beginPath();ctx.arc(player.x-cameraX+player.w/2+player.facing*38,player.y+36,player.heavyTimer>0?42:30,-1,1);ctx.stroke()}}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();if(!gameOver&&!levelComplete)requestAnimationFrame(loop)}
refreshHQ();
